### ISSUE TITLE
Qwen Part

### ISSUE THREAD

**Issue by qingyuanxingsi** [FreedomIntelligence/ALLaVA#8]
Great work! It seems that the code didn't include the qwen llm backbone part?

**Comment by g-h-chen** [comment]
Nope it didn't. Our final model is based on Phi2-2.7B.

**Comment by qingyuanxingsi** [comment]
> Nope it didn't. Our final model is based on Phi2-2.7B.

Your paper mentioned qwen 1.8b as a baseline?

**Comment by g-h-chen** [comment]
> Your paper mentioned qwen 1.8b as a baseline?

Yes we did. In our experiment, **Phi2-2.7B** slightly outperforms **StableLM2-1.6B**, and largely outperforms **Qwen-1.8B**. However, we are not planning to release the checkpoints based on StableLM or Qwen. You can simply use our training data (ALL open-sourced) to reproduce the results.

**Comment by qingyuanxingsi** [comment]
@g-h-chen Checkpoints are not important. Would you be so kind as to release the code related, especially for qwen?

**Comment by g-h-chen** [comment]
Hi @qingyuanxingsi , there is still some work to do in order to release the code. Currently, please refer to the following sketch to adapt the current code to Qwen:

1. In `allava/model/language_model`, create a folder `qwen`. Then put `modeling_qwen.py` and `configuration_qwen.py` into the folder. These two files are from the official Qwen repo.
2. In `allava/model/language_model`, create a file `llava_qwen.py`. This file is similar to `llava_phi.py`. Basically you only need to replace `phi` with `qwen` and `Phi` with `Qwen`.
3. In `allava/model/__init__.py`, add a line `from .language_model.llava_qwen import LlavaQwenForCausalLM, LlavaQwenConfig`.
4. In `allava/serve/cli.py`, [init_component()](https://github.com/FreedomIntelligence/ALLaVA/blob/b4c34db2096d71e484a17240e20b323d1543760d/allava/serve/cli.py#L34), add an `if` condition to load Qwen model.

That's all the steps needed to load a qwen-based model. Sorry for the inconvenience bought!

Best,
Guiming
